# -*- coding: utf-8 -*-
"""Bulk-RNA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gj0FILk26YGpHP3MnrFiBJ1JC5y7MmJj
"""

import pandas as pd
import numpy as np

def normalize_data(data):
    library_sizes = data.sum(axis=0)
    effective_library_size = np.exp(np.mean(np.log(library_sizes)))
    normalization_factors = library_sizes / effective_library_size
    normalized_data = data.div(normalization_factors, axis=1)
    return normalized_data

filepath = '/content/drive/MyDrive/Colab/GSE224008_exp.csv'

data = pd.read_csv(filepath, index_col=0)

data_normalized = normalize_data(data)

print(data_normalized)

from scipy import stats
def perform_differential_analysis(data):
    significant_genes = []

    for gene_id, expression_levels in data.iterrows():
        t_statistic, p_value = stats.ttest_ind(expression_levels, 0)
        if p_value < 0.05:
            significant_genes.append(gene_id)
    return significant_genes

significant_genes = perform_differential_analysis(data_normalized)

print("Significant genes:", len(significant_genes))
