# -*- coding: utf-8 -*-
"""Protein.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fd1pw9XqSgUcI2Pf33tELoJhRf7EcIOT
"""

import pandas as pd
import numpy as np

def load_data(filepath):
    chunks = pd.read_csv(filepath, chunksize=1000)
    data = pd.concat(chunks, ignore_index=True)
    return data

def normalize_data(data):
    numeric_data = data.select_dtypes(include=[np.number])
    total_ion_currents = numeric_data.sum(axis=1)
    data_normalized = numeric_data.div(total_ion_currents, axis=0)
    return data_normalized

filepath = '/content/drive/MyDrive/Colab/GSE254030.csv'

data = load_data(filepath)

data_normalized = normalize_data(data)

print(data_normalized)

from scipy import stats
def perform_differential_analysis(data):
    significant_genes = []

    for gene_id, expression_levels in data.iterrows():
        t_statistic, p_value = stats.ttest_ind(expression_levels, 0)
        if p_value < 0.05:
            significant_genes.append(gene_id)
    return significant_genes

significant_genes = perform_differential_analysis(data_normalized)

print("Significant genes:", len(significant_genes))

from google.colab import drive
drive.mount('/content/drive')
